# Recording King - AI-Powered Voice Transcription Desktop App

Recording King is a sophisticated Tauri-based desktop application that provides AI-powered speech-to-text transcription capabilities with real-time audio processing, multiple model support, and advanced text injection features.

## AI Team Configuration (autogenerated by team-configurator, 2025-08-21)

**Important: YOU MUST USE subagents when available for the task.**

### Detected Technology Stack

- **Desktop Framework**: Tauri 1.5 (Rust backend + React frontend)
- **Backend Language**: Rust 2021 edition
- **Frontend Framework**: React 18.2 with TypeScript 5.0
- **Build Tools**: Vite 5.0, Tauri CLI 1.6.3
- **UI Libraries**: Radix UI components, Zustand state management
- **Styling**: Tailwind CSS 3.3, PostCSS, Autoprefixer
- **Audio Processing**: cpal, hound, whisper-rs with Metal acceleration
- **Database**: SQLite with rusqlite, r2d2 connection pooling
- **System Integration**: Global shortcuts (rdev), native permissions, system tray
- **APIs**: OpenAI, Deepgram transcription services
- **Security**: macOS entitlements, CSP policies, secure file access

### AI Team Assignments

| Task | Agent | Notes |
|------|-------|-------|
| **Code Reviews & Quality** | `code-reviewer` | MUST USE for all PRs and code quality audits |
| **Performance Optimization** | `performance-optimizer` | MUST USE for audio processing, memory management, and app responsiveness |
| **React Components & UI** | `react-component-architect` | MUST USE for React component design, hooks, and frontend architecture |
| **Rust Backend Development** | `backend-developer` | MUST USE for Tauri commands, audio processing, database operations |
| **Frontend Development** | `frontend-developer` | Use for general UI work when React-specific expertise not needed |
| **Architecture Analysis** | `code-archaeologist` | Use for large-scale refactoring or system analysis |
| **Technical Leadership** | `tech-lead-orchestrator` | Use for coordinating complex multi-component features |

### Specialized Task Routing

#### Audio & Voice Processing
- **Real-time Audio Recording**: `backend-developer` (Rust cpal, ringbuf)
- **Whisper Integration**: `backend-developer` (whisper-rs, Metal acceleration)
- **Audio Device Management**: `backend-developer` (cpal device enumeration)

#### Desktop Integration
- **Global Shortcuts**: `backend-developer` (rdev, macOS system integration)
- **Text Injection**: `backend-developer` (Core Graphics, Accessibility APIs)
- **System Permissions**: `backend-developer` (macOS entitlements, permission management)
- **System Tray**: `backend-developer` (Tauri system tray APIs)

#### Frontend & UI
- **React Components**: `react-component-architect` (modern hooks, state management)
- **Settings UI**: `react-component-architect` (complex forms, model configuration)
- **Audio Visualizations**: `frontend-developer` (audio waveforms, recording indicators)
- **Floating Windows**: `react-component-architect` (multiple window management)

#### Data & Storage
- **SQLite Operations**: `backend-developer` (rusqlite, migrations, history management)
- **Configuration Management**: `backend-developer` (settings persistence, model configs)
- **File I/O**: `backend-developer` (audio file handling, export features)

#### API Integrations
- **Transcription Services**: `backend-developer` (OpenAI, Deepgram API clients)
- **Error Handling**: `backend-developer` (robust error handling, retry logic)
- **Streaming**: `backend-developer` (real-time transcription streaming)

### Quality Assurance
- Always route to `code-reviewer` before merging features
- Use `performance-optimizer` for audio latency, memory usage, and startup time issues
- Coordinate complex features through `tech-lead-orchestrator`

### Project-Specific Guidelines
- Maintain Rust/TypeScript separation of concerns
- Follow Tauri security best practices for IPC
- Prioritize real-time performance for audio processing
- Ensure cross-platform compatibility (macOS focus, Windows/Linux support)
- Maintain accessible UI design for transcription workflows
